### ISSUE TITLE
Direct download

### ISSUE THREAD

**Issue by dries007** [DimitrodAM/cf-updater#1]
First of all, cool stuff.

If you want to directly download a mod, you can use the internal CurseForge/Twitch API.
Here is some nice documentation: https://twitchappapi.docs.apiary.io/

Making this work without a browser would be nice for servers.

Just be aware that it's very likely you'll get locked out at some point since Overwolf bought CurseForge. I've heard they're not very happy about the (third party) bandwith usage from the API. Nothing is certain though, so have at it in the meantime :)

**Comment by DimiDimit** [comment]
Thanks a lot, I didn't know about that API! I'll make it use it for the downloads, and I might look into refactoring the entire project to use this instead of CFWidget.

**Comment by DimiDimit** [comment]
That should do it, though I haven't tested it extensively.

**Comment by DimiDimit** [comment]
I don't know how I missed this. I'm thinking of parallelizing it to increase its speed even further!

**Comment by dries007** [comment]
You can thank Reddit, found the project there :smile:.
Just a last FYI: Make sure you set a user agent, or Cloudflare will IP ban you.

**Comment by DimiDimit** [comment]
Should be fixed in 00763f0, though I'm not sure whether it'll work.
