### ISSUE TITLE
Specifying Forge and Fabric versions

### ISSUE THREAD

**Issue by BlayZin** [DimitrodAM/cf-updater#8]
Unless I have overlooked something, I don't see a way to say I only want Forge versions, for example.

Here's a mod where this would be important: https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map

**Comment by DimiDimit** [comment]
Oh, I completely missed this! Seems easy enough.

**Comment by DimiDimit** [comment]
This should work, but some mods may not have `Fabric` in their version tags, which could get tricky.
If you have any problems, comment on this issue.
